"""Write every season's top ten under the raced-out continuation model.

The site shows one season at a time, which is the right shape for reading a
title fight and the wrong shape for scanning seventy-six of them. This dumps the
lot to a single Markdown file so the effect of the form dynamics can be reviewed
end to end — including the seasons where the model disagrees with history.

    python scripts/export_championships.py --out updated-championship.md
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sqlalchemy import create_engine, text  # noqa: E402

from app.core.config import settings  # noqa: E402

#: Standings are quoted to this depth. Ten is the modern points-paying field.
TOP_N = 10

HEADER = """# Updated championships

Every season's top ten under the **continuation** model: the races that were
actually run are kept exactly as they happened, and the remainder of a 24-race
calendar is raced out from each driver's end-of-season form, with that form
drifting race by race rather than being frozen.

Points are on the modern scale (25-18-15-...), so they will not match the
contemporary standings even before anything is simulated. `P(title)` is the
share of iterations in which the driver ends up champion.

- **bold** marks the driver the model makes champion.
- (*) marks the driver who actually won the title that year.
- A season that already ran the full 24 races has no remainder to race, so its
  table is the season as it happened, rescored.

Generated by `scripts/export_championships.py`.
"""


def current_run(conn) -> int:
    run = conn.execute(
        text("SELECT run_id FROM sim_runs WHERE is_complete = 1 ORDER BY run_id DESC LIMIT 1")
    ).scalar_one_or_none()
    if run is None:
        raise SystemExit("no complete run in the database — run scripts/run_simulations.py")
    return int(run)


def seasons(conn, run: int) -> list[tuple[int, int, int | None]]:
    return [
        (int(r.year), int(r.n_races), r.actual_champion_driver_id)
        for r in conn.execute(
            text(
                """
                SELECT s.year, s.n_races, s.actual_champion_driver_id
                FROM seasons s
                WHERE s.n_races > 0
                  AND EXISTS (
                      SELECT 1 FROM season_continuation_sim c
                      WHERE c.run_id = :run AND c.year = s.year
                  )
                ORDER BY s.year
                """
            ),
            {"run": run},
        ).all()
    ]


def standings(conn, run: int, year: int) -> list:
    """Continuation rows for one season, best expected total first."""
    return conn.execute(
        text(
            """
            SELECT c.driver_id, c.points_mean, c.banked_points, c.wins_mean,
                   c.podiums_mean, c.p_champion, c.extra_races, c.form_strength,
                   d.forename, d.surname, cn.name AS constructor
            FROM season_continuation_sim c
            JOIN drivers d ON d.driver_id = c.driver_id
            LEFT JOIN season_driver_sim sds
              ON sds.run_id = c.run_id AND sds.year = c.year
             AND sds.driver_id = c.driver_id
            LEFT JOIN constructors cn ON cn.constructor_id = sds.constructor_id
            WHERE c.run_id = :run AND c.year = :year
            ORDER BY c.points_mean DESC, c.wins_mean DESC
            LIMIT :n
            """
        ),
        {"run": run, "year": year, "n": TOP_N},
    ).all()


def season_block(conn, run: int, year: int, n_races: int, champion_id: int | None) -> str:
    rows = standings(conn, run, year)
    if not rows:
        return ""

    extra = int(rows[0].extra_races or 0)
    # Computed for full calendars too: with nothing left to race the standings
    # are just the season rescored on modern points, which is itself enough to
    # move a title.
    winner = max(rows, key=lambda r: r.p_champion).driver_id

    lines = [f"## {year}", ""]
    if extra:
        lines.append(
            f"{n_races} races run, {extra} raced out to reach 24."
        )
    else:
        lines.append(f"{n_races} races — already a full calendar, nothing raced out.")
    lines.append("")
    lines.append("| # | Driver | Constructor | Points | Banked | Wins | P(title) |")
    lines.append("|---|---|---|---|---|---|---|")

    for i, r in enumerate(rows, 1):
        name = f"{r.forename} {r.surname}"
        if r.driver_id == winner:
            name = f"**{name}**"
        if champion_id is not None and r.driver_id == champion_id:
            name = f"{name} (*)"
        lines.append(
            f"| {i} | {name} | {r.constructor or '—'} | {r.points_mean:.1f} "
            f"| {r.banked_points:.0f} | {r.wins_mean:.1f} | {r.p_champion:.1%} |"
        )

    # Only worth calling out where the model actually overturns the record; a
    # season it agrees with needs no annotation.
    if champion_id is not None and winner != champion_id:
        taken = next(r for r in rows if r.driver_id == winner)
        how = (
            f"at {taken.p_champion:.0%}"
            if extra
            else "on the modern points scale alone — nothing was raced out"
        )
        lines.append("")
        lines.append(
            f"> The model gives this one to **{taken.forename} {taken.surname}** "
            f"{how}."
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, default=settings.db_path)
    parser.add_argument("--out", type=Path, default=Path("updated-championship.md"))
    args = parser.parse_args()

    engine = create_engine(f"sqlite:///{args.db}", future=True)
    with engine.connect() as conn:
        run = current_run(conn)
        blocks = [
            season_block(conn, run, year, n_races, champion_id)
            for year, n_races, champion_id in seasons(conn, run)
        ]

    args.out.write_text(
        HEADER + "\n" + "\n".join(b for b in blocks if b), encoding="utf-8"
    )
    print(f"wrote {args.out} from run {run}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
